spring:
  task:
    scheduling:
      pool:
        size: 5
  application:
    name: KnittingFactory
  datasource:
    url: jdbc:postgresql://192.168.0.2:5432/knitting_factory?currentSchema=knitting_factory
    username: anton
    password: Oral_speach12
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          create_namespaces: true
