spring:
  task:
    scheduling:
      pool:
        size: 5
  application:
    name: knitting-factory-mes
  datasource:
    url: jdbc:postgresql://localhost:5432/knitting_factory?currentSchema=knitting_factory_mes
    username: postgres
    password: postgres
  security:
    user:
      password: kazantip2009