spring:
  task:
    scheduling:
      pool:
        size: 5
  application:
    name: knitting-factory-mes
  datasource:
    url: jdbc:postgresql://localhost:5432/knitting_factory?currentSchema=knitting_factory
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          create_namespaces: true
